name: harhan_laundry
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  swipeable_page_route: ^0.2.6
  firebase_storage: ^10.2.17
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  badges: ^2.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/bag_treatment/
    - assets/image/hlm/
    - assets/image/sandal/
    - assets/image/shoes/


